import Head from 'next/head'

import Avatar from '../components/Avatar'
import Footer from '../components/Footer'

const avatar = "/images/profile-img.jpg"

const google_logo = "/images/google.png"

import { MicrophoneIcon, ViewGridIcon } from '@heroicons/react/solid'
import { SearchIcon } from '@heroicons/react/outline'
import Image from 'next/image'
import {useRef} from 'react'
import {useRouter} from 'next/router'

export default function Home() {
  const searchInputRef = useRef(null)
  const router = useRouter()

  const search = (e) =>{
    e.preventDefault()

    const term = searchInputRef.current.value

    if (!term) return

    router.push(`/search?term=${term}`)

  }

  return (
    <div className="flex flex-col justify-between h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*Header*/}
      <header className="flex items-center justify-between p-5 text-sm">
      {/*left*/}
      <div className="flex space-x-4 items-center">
        <p className="nav-links">
          About
        </p>
        <p className="nav-links">
          Store
        </p>
      </div>
      
      {/*right*/}
      <div className="flex space-x-4 items-center">
        <p className="nav-links">
        Gmail
        </p>
        
        <p className="nav-links">
        Images
        </p>
        
        <ViewGridIcon className="w-10 h-10 p-2 rounded-full hover:bg-gray-100" />
        
        <Avatar url={avatar}/>
      </div>
      </header>

      <main>
        <form className="flex flex-col items-center flex-grow max-w-4/5">
          <Image src={google_logo}
            alt="google"
            height={100}
            width={300}/>

          <div className="flex items-center border border-gray-200 px-3 py-2 mt-8 w-full hover:shadow-lg focus-within:shadow-lg rounded-full max-w-md sm:max-w-xl lg:max-w-2xl">
            <SearchIcon
             className="text-gray-500 h-5 mr-2"/>

            <input type="text" ref={searchInputRef}
              className="flex-grow focus:outline-none" />

            <MicrophoneIcon className="h-5" />

          </div>

          <div className="flex flex-col space-y-2 w-1/2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">

            <button onClick={search} className="btn">Google Search</button>

            <button onClick={search} className="btn">I am feeling lucky</button>

          </div>

        </form> 
      </main>
      
      <Footer />
    </div>
  )
}
