import Head from 'next/head'
import Image from 'next/image'

import Avatar from '../components/Avatar'

const avatar = "http://localhost:3000/images/profile-img.jpg"

import { ViewGridIcon, MicrophoneIcone } from '@heroicons/react/solid'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*Header*/}
      <header className="flex items-center justify-between p-5 text-sm">
      {/*left*/}
      <div className="flex space-x-4 items-center">
        <p className="nav-links">
          About
        </p>
        <p className="nav-links">
          Store
        </p>
      </div>
      
      {/*right*/}
      <div className="flex space-x-4 items-center">
        <p className="nav-links">
        Gmail
        </p>
        
        <p className="nav-links">
        Images
        </p>
        
        <ViewGridIcon className="w-10 h-10 p-2 rounded-full hover:bg-gray-100" />
        
        <Avatar url={avatar}/>
      </div>
      </header>

      <main>
       
      </main>

      <footer>
      
      </footer>
    </div>
  )
}
